export const SAVE_PEOPLE = "SAVE_PEOPLE";
export const SHOW_MORE_PEOPLE = "SHOW_MORE_PEOPLE";
export const ADD_SEARCH_CRITERIA = "ADD_SEARCH_CRITERIA";
export const CLEAR_SEARCH_CRITERIA = "CLEAR_SEARCH_CRITERIA";
export const SAVE_FILTERED_PEOPLE = "SAVE_FILTERED_PEOPLE";
export const RESET_MAX_ITEMS_ON_PAGE_COUNT = "RESET_MAX_ITEMS_ON_PAGE_COUNT";
export const ADD_FILTER_CRITERIA_PROFFESIONS =
  "ADD_FILTER_CRITERIA_PROFFESIONS";
export const CLEAR_FILTER_CRITERIA_PROFFESIONS =
  "CLEAR_FILTER_CRITERIA_PROFFESIONS";
